id: IB9543D82
legacy_id: P002979
ocr_import_info:
  bdrc_scan_id: W1CZ1209
  source: bdrc
  ocr_info:
    timestamp: '2020-03-22T14:20:40'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-08-30T18:59:39.850295+00:00'
last_modified: 2022-08-31 02:59:51.557059
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W1CZ1209
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW1CZ1209
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: ལཱུ་ཨི་པའི་མངོན་པར་རྟོགས་པའི་འགྲེལ་པའི་ཊི་ཀ་ཁྱད་པར་གསལ་བྱེད།
statistics:
  ocr_word_mean_confidence_index: 0.493180308997861
  ocr_word_median_confidence_index: 0.4300000071525574
quality: null
bases:
  I1CZ2075:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1CZ2075
      total_pages: 70
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I1CZ2075.txt
    statistics:
      ocr_word_median_confidence_index: 0.4300000071525574
      ocr_word_mean_confidence_index: 0.493180308997861
    legacy_id: v001
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
