id: P002979
initial_creation_type: ocr
created_at: 22/03/2020
last_modified_at: 24/11/2021
source_metadata:
  id: bdr:W1CZ1209
  title: ལཱུ་ཨི་པའི་མངོན་པར་རྟོགས་པའི་འགྲེལ་པའི་ཊི་ཀ་ཁྱད་པར་གསལ་བྱེད་
  author: ''
  volumes:
    e7e61490607f47eabf60043378d81ccb:
      image_group_id: I1CZ2075
      title: ''
      volume_number: 1
      total_pages: 70
      base_file: v001.txt
